<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: access_path.proto

namespace GPBMetadata;

class AccessPath
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4f0a116163636573735f706174682e70726f746f12057479706573222b" .
            "0a0a41636365737350617468120f0a076164647265737318012001280c12" .
            "0c0a047061746818022001280c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

