<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_state_blob.proto

namespace GPBMetadata;

class AccountStateBlob
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Proof::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a186163636f756e745f73746174655f626c6f622e70726f746f12" .
            "05747970657322200a104163636f756e745374617465426c6f62120c0a04" .
            "626c6f6218012001280c22780a154163636f756e74537461746557697468" .
            "50726f6f66120f0a0776657273696f6e18012001280412250a04626c6f62" .
            "18022001280b32172e74797065732e4163636f756e745374617465426c6f" .
            "6212270a0570726f6f6618032001280b32182e74797065732e4163636f75" .
            "6e74537461746550726f6f66620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

