<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace GPBMetadata;

class Events
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\AccessPath::initOnce();
        \GPBMetadata\Proof::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc020a0c6576656e74732e70726f746f120574797065731a0b70726f6f" .
            "662e70726f746f225c0a054576656e7412260a0b6163636573735f706174" .
            "6818012001280b32112e74797065732e4163636573735061746812170a0f" .
            "73657175656e63655f6e756d62657218022001280412120a0a6576656e74" .
            "5f6461746118032001280c2281010a0e4576656e745769746850726f6f66" .
            "121b0a137472616e73616374696f6e5f76657273696f6e18012001280412" .
            "130a0b6576656e745f696e646578180220012804121b0a056576656e7418" .
            "032001280b320c2e74797065732e4576656e7412200a0570726f6f661804" .
            "2001280b32112e74797065732e4576656e7450726f6f66222a0a0a457665" .
            "6e74734c697374121c0a066576656e747318012003280b320c2e74797065" .
            "732e4576656e7422420a114576656e7473466f7256657273696f6e73122d" .
            "0a126576656e74735f666f725f76657273696f6e18012003280b32112e74" .
            "797065732e4576656e74734c697374620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

