<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language_storage.proto

namespace GPBMetadata;

class LanguageStorage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a520a166c616e67756167655f73746f726167652e70726f746f12057479" .
            "70657322290a084d6f64756c654964120f0a076164647265737318012001" .
            "280c120c0a046e616d65180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

