<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mempool_status.proto

namespace GPBMetadata;

class MempoolStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a146d656d706f6f6c5f7374617475732e70726f746f12076d656d" .
            "706f6f6c2a96010a1b4d656d706f6f6c4164645472616e73616374696f6e" .
            "53746174757312090a0556616c6964100012170a13496e73756666696369" .
            "656e7442616c616e6365100112140a10496e76616c69645365714e756d62" .
            "6572100212110a0d4d656d706f6f6c497346756c6c100312170a13546f6f" .
            "4d616e795472616e73616374696f6e73100412110a0d496e76616c696455" .
            "70646174651005620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

