<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_info.proto

namespace GPBMetadata;

class TransactionInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a167472616e73616374696f6e5f696e666f2e70726f746f120574" .
            "7970657322760a0f5472616e73616374696f6e496e666f121f0a17736967" .
            "6e65645f7472616e73616374696f6e5f6861736818012001280c12170a0f" .
            "73746174655f726f6f745f6861736818022001280c12170a0f6576656e74" .
            "5f726f6f745f6861736818032001280c12100a086761735f757365641804" .
            "20012804620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

