<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator_public_keys.proto

namespace GPBMetadata;

class ValidatorPublicKeys
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4010a1b76616c696461746f725f7075626c69635f6b6579732e70726f" .
            "746f120574797065732295010a1356616c696461746f725075626c69634b" .
            "65797312170a0f6163636f756e745f6164647265737318012001280c121c" .
            "0a14636f6e73656e7375735f7075626c69635f6b657918022001280c1222" .
            "0a1a6e6574776f726b5f7369676e696e675f7075626c69635f6b65791803" .
            "2001280c12230a1b6e6574776f726b5f6964656e746974795f7075626c69" .
            "635f6b657918042001280c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

