<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator_change.proto

namespace GPBMetadata;

class ValidatorChange
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Events::initOnce();
        \GPBMetadata\LedgerInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acd010a1676616c696461746f725f6368616e67652e70726f746f120574" .
            "797065731a116c65646765725f696e666f2e70726f746f2290010a1d5661" .
            "6c696461746f724368616e67654576656e745769746850726f6f66123e0a" .
            "156c65646765725f696e666f5f776974685f7369677318012001280b321f" .
            "2e74797065732e4c6564676572496e666f576974685369676e6174757265" .
            "73122f0a106576656e745f776974685f70726f6f6618022001280b32152e" .
            "74797065732e4576656e745769746850726f6f66620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

