<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_state_blob.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.AccountStateBlob</code>
 */
class AccountStateBlob extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes blob = 1;</code>
     */
    private $blob = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $blob
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AccountStateBlob::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes blob = 1;</code>
     * @return string
     */
    public function getBlob()
    {
        return $this->blob;
    }

    /**
     * Generated from protobuf field <code>bytes blob = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBlob($var)
    {
        GPBUtil::checkString($var, False);
        $this->blob = $var;

        return $this;
    }

}

