<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_state_blob.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.AccountStateWithProof</code>
 */
class AccountStateWithProof extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 version = 1;</code>
     */
    private $version = 0;
    /**
     * Generated from protobuf field <code>.types.AccountStateBlob blob = 2;</code>
     */
    private $blob = null;
    /**
     * Generated from protobuf field <code>.types.AccountStateProof proof = 3;</code>
     */
    private $proof = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version
     *     @type \Types\AccountStateBlob $blob
     *     @type \Types\AccountStateProof $proof
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AccountStateBlob::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.AccountStateBlob blob = 2;</code>
     * @return \Types\AccountStateBlob
     */
    public function getBlob()
    {
        return $this->blob;
    }

    /**
     * Generated from protobuf field <code>.types.AccountStateBlob blob = 2;</code>
     * @param \Types\AccountStateBlob $var
     * @return $this
     */
    public function setBlob($var)
    {
        GPBUtil::checkMessage($var, \Types\AccountStateBlob::class);
        $this->blob = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.AccountStateProof proof = 3;</code>
     * @return \Types\AccountStateProof
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     * Generated from protobuf field <code>.types.AccountStateProof proof = 3;</code>
     * @param \Types\AccountStateProof $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkMessage($var, \Types\AccountStateProof::class);
        $this->proof = $var;

        return $this;
    }

}

