<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Account state as a whole.
 * After execution, updates to accounts are passed in this form to storage for
 * persistence.
 *
 * Generated from protobuf message <code>types.AccountState</code>
 */
class AccountState extends \Google\Protobuf\Internal\Message
{
    /**
     * Account address
     *
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    private $address = '';
    /**
     * Account state blob
     *
     * Generated from protobuf field <code>bytes blob = 2;</code>
     */
    private $blob = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *           Account address
     *     @type string $blob
     *           Account state blob
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Account address
     *
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Account address
     *
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Account state blob
     *
     * Generated from protobuf field <code>bytes blob = 2;</code>
     * @return string
     */
    public function getBlob()
    {
        return $this->blob;
    }

    /**
     * Account state blob
     *
     * Generated from protobuf field <code>bytes blob = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBlob($var)
    {
        GPBUtil::checkString($var, False);
        $this->blob = $var;

        return $this;
    }

}

