<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proof.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.AccumulatorProof</code>
 */
class AccumulatorProof extends \Google\Protobuf\Internal\Message
{
    /**
     * The bitmap indicating which siblings are default. 1 means non-default and
     * 0 means default. The LSB corresponds to the sibling at the bottom of the
     * accumulator. The leftmost 1-bit corresponds to the sibling at the level
     * just below root level in the accumulator, since this one is always
     * non-default.
     *
     * Generated from protobuf field <code>uint64 bitmap = 1;</code>
     */
    private $bitmap = 0;
    /**
     * The non-default siblings. The ones near the root are at the beginning of
     * the list.
     *
     * Generated from protobuf field <code>repeated bytes non_default_siblings = 2;</code>
     */
    private $non_default_siblings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $bitmap
     *           The bitmap indicating which siblings are default. 1 means non-default and
     *           0 means default. The LSB corresponds to the sibling at the bottom of the
     *           accumulator. The leftmost 1-bit corresponds to the sibling at the level
     *           just below root level in the accumulator, since this one is always
     *           non-default.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $non_default_siblings
     *           The non-default siblings. The ones near the root are at the beginning of
     *           the list.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proof::initOnce();
        parent::__construct($data);
    }

    /**
     * The bitmap indicating which siblings are default. 1 means non-default and
     * 0 means default. The LSB corresponds to the sibling at the bottom of the
     * accumulator. The leftmost 1-bit corresponds to the sibling at the level
     * just below root level in the accumulator, since this one is always
     * non-default.
     *
     * Generated from protobuf field <code>uint64 bitmap = 1;</code>
     * @return int|string
     */
    public function getBitmap()
    {
        return $this->bitmap;
    }

    /**
     * The bitmap indicating which siblings are default. 1 means non-default and
     * 0 means default. The LSB corresponds to the sibling at the bottom of the
     * accumulator. The leftmost 1-bit corresponds to the sibling at the level
     * just below root level in the accumulator, since this one is always
     * non-default.
     *
     * Generated from protobuf field <code>uint64 bitmap = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBitmap($var)
    {
        GPBUtil::checkUint64($var);
        $this->bitmap = $var;

        return $this;
    }

    /**
     * The non-default siblings. The ones near the root are at the beginning of
     * the list.
     *
     * Generated from protobuf field <code>repeated bytes non_default_siblings = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNonDefaultSiblings()
    {
        return $this->non_default_siblings;
    }

    /**
     * The non-default siblings. The ones near the root are at the beginning of
     * the list.
     *
     * Generated from protobuf field <code>repeated bytes non_default_siblings = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNonDefaultSiblings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->non_default_siblings = $arr;

        return $this;
    }

}

