<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.ArithmeticError</code>
 */
class ArithmeticError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.ArithmeticError.ArithmeticErrorType error_code = 1;</code>
     */
    private $error_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\VmErrors::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.ArithmeticError.ArithmeticErrorType error_code = 1;</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>.types.ArithmeticError.ArithmeticErrorType error_code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkEnum($var, \Types\ArithmeticError_ArithmeticErrorType::class);
        $this->error_code = $var;

        return $this;
    }

}

