<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

if (false) {
    /**
     * This class is deprecated. Use Types\ArithmeticError\ArithmeticErrorType instead.
     * @deprecated
     */
    class ArithmeticError_ArithmeticErrorType {}
}
class_exists(ArithmeticError\ArithmeticErrorType::class);
@trigger_error('Types\ArithmeticError_ArithmeticErrorType is deprecated and will be removed in the next major release. Use Types\ArithmeticError\ArithmeticErrorType instead', E_USER_DEPRECATED);

