<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

use UnexpectedValueException;

/**
 * Errors that can arise from binary decoding (deserialization)
 *
 * Protobuf type <code>types.BinaryError</code>
 */
class BinaryError
{
    /**
     * Generated from protobuf enum <code>UnknownBinaryError = 0;</code>
     */
    const UnknownBinaryError = 0;
    /**
     * Generated from protobuf enum <code>Malformed = 1;</code>
     */
    const Malformed = 1;
    /**
     * Generated from protobuf enum <code>BadMagic = 2;</code>
     */
    const BadMagic = 2;
    /**
     * Generated from protobuf enum <code>UnknownVersion = 3;</code>
     */
    const UnknownVersion = 3;
    /**
     * Generated from protobuf enum <code>UnknownTableType = 4;</code>
     */
    const UnknownTableType = 4;
    /**
     * Generated from protobuf enum <code>UnknownSignatureType = 5;</code>
     */
    const UnknownSignatureType = 5;
    /**
     * Generated from protobuf enum <code>UnknownSerializedType = 6;</code>
     */
    const UnknownSerializedType = 6;
    /**
     * Generated from protobuf enum <code>UnknownOpcode = 7;</code>
     */
    const UnknownOpcode = 7;
    /**
     * Generated from protobuf enum <code>BadHeaderTable = 8;</code>
     */
    const BadHeaderTable = 8;
    /**
     * Generated from protobuf enum <code>UnexpectedSignatureType = 9;</code>
     */
    const UnexpectedSignatureType = 9;
    /**
     * Generated from protobuf enum <code>DuplicateTable = 10;</code>
     */
    const DuplicateTable = 10;

    private static $valueToName = [
        self::UnknownBinaryError => 'UnknownBinaryError',
        self::Malformed => 'Malformed',
        self::BadMagic => 'BadMagic',
        self::UnknownVersion => 'UnknownVersion',
        self::UnknownTableType => 'UnknownTableType',
        self::UnknownSignatureType => 'UnknownSignatureType',
        self::UnknownSerializedType => 'UnknownSerializedType',
        self::UnknownOpcode => 'UnknownOpcode',
        self::BadHeaderTable => 'BadHeaderTable',
        self::UnexpectedSignatureType => 'UnexpectedSignatureType',
        self::DuplicateTable => 'DuplicateTable',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

