<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

if (false) {
    /**
     * This class is deprecated. Use Types\DynamicReferenceError\DynamicReferenceErrorType instead.
     * @deprecated
     */
    class DynamicReferenceError_DynamicReferenceErrorType {}
}
class_exists(DynamicReferenceError\DynamicReferenceErrorType::class);
@trigger_error('Types\DynamicReferenceError_DynamicReferenceErrorType is deprecated and will be removed in the next major release. Use Types\DynamicReferenceError\DynamicReferenceErrorType instead', E_USER_DEPRECATED);

