<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An event emitted from a smart contract
 *
 * Generated from protobuf message <code>types.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.AccessPath access_path = 1;</code>
     */
    private $access_path = null;
    /**
     * Generated from protobuf field <code>uint64 sequence_number = 2;</code>
     */
    private $sequence_number = 0;
    /**
     * Generated from protobuf field <code>bytes event_data = 3;</code>
     */
    private $event_data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\AccessPath $access_path
     *     @type int|string $sequence_number
     *     @type string $event_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.AccessPath access_path = 1;</code>
     * @return \Types\AccessPath
     */
    public function getAccessPath()
    {
        return $this->access_path;
    }

    /**
     * Generated from protobuf field <code>.types.AccessPath access_path = 1;</code>
     * @param \Types\AccessPath $var
     * @return $this
     */
    public function setAccessPath($var)
    {
        GPBUtil::checkMessage($var, \Types\AccessPath::class);
        $this->access_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sequence_number = 2;</code>
     * @return int|string
     */
    public function getSequenceNumber()
    {
        return $this->sequence_number;
    }

    /**
     * Generated from protobuf field <code>uint64 sequence_number = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequenceNumber($var)
    {
        GPBUtil::checkUint64($var);
        $this->sequence_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes event_data = 3;</code>
     * @return string
     */
    public function getEventData()
    {
        return $this->event_data;
    }

    /**
     * Generated from protobuf field <code>bytes event_data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEventData($var)
    {
        GPBUtil::checkString($var, False);
        $this->event_data = $var;

        return $this;
    }

}

