<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An event along with the proof for the event
 *
 * Generated from protobuf message <code>types.EventWithProof</code>
 */
class EventWithProof extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 transaction_version = 1;</code>
     */
    private $transaction_version = 0;
    /**
     * Generated from protobuf field <code>uint64 event_index = 2;</code>
     */
    private $event_index = 0;
    /**
     * Generated from protobuf field <code>.types.Event event = 3;</code>
     */
    private $event = null;
    /**
     * Generated from protobuf field <code>.types.EventProof proof = 4;</code>
     */
    private $proof = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $transaction_version
     *     @type int|string $event_index
     *     @type \Types\Event $event
     *     @type \Types\EventProof $proof
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 transaction_version = 1;</code>
     * @return int|string
     */
    public function getTransactionVersion()
    {
        return $this->transaction_version;
    }

    /**
     * Generated from protobuf field <code>uint64 transaction_version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTransactionVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->transaction_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 event_index = 2;</code>
     * @return int|string
     */
    public function getEventIndex()
    {
        return $this->event_index;
    }

    /**
     * Generated from protobuf field <code>uint64 event_index = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->event_index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.Event event = 3;</code>
     * @return \Types\Event
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.types.Event event = 3;</code>
     * @param \Types\Event $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Types\Event::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.EventProof proof = 4;</code>
     * @return \Types\EventProof
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     * Generated from protobuf field <code>.types.EventProof proof = 4;</code>
     * @param \Types\EventProof $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkMessage($var, \Types\EventProof::class);
        $this->proof = $var;

        return $this;
    }

}

