<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A list of EventList's, each representing all events for a transaction.
 *
 * Generated from protobuf message <code>types.EventsForVersions</code>
 */
class EventsForVersions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .types.EventsList events_for_version = 1;</code>
     */
    private $events_for_version;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\EventsList[]|\Google\Protobuf\Internal\RepeatedField $events_for_version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .types.EventsList events_for_version = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEventsForVersion()
    {
        return $this->events_for_version;
    }

    /**
     * Generated from protobuf field <code>repeated .types.EventsList events_for_version = 1;</code>
     * @param \Types\EventsList[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEventsForVersion($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\EventsList::class);
        $this->events_for_version = $arr;

        return $this;
    }

}

