<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_with_proof.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.GetTransactionsResponse</code>
 */
class GetTransactionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.TransactionListWithProof txn_list_with_proof = 1;</code>
     */
    private $txn_list_with_proof = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\TransactionListWithProof $txn_list_with_proof
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetWithProof::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.TransactionListWithProof txn_list_with_proof = 1;</code>
     * @return \Types\TransactionListWithProof
     */
    public function getTxnListWithProof()
    {
        return $this->txn_list_with_proof;
    }

    /**
     * Generated from protobuf field <code>.types.TransactionListWithProof txn_list_with_proof = 1;</code>
     * @param \Types\TransactionListWithProof $var
     * @return $this
     */
    public function setTxnListWithProof($var)
    {
        GPBUtil::checkMessage($var, \Types\TransactionListWithProof::class);
        $this->txn_list_with_proof = $var;

        return $this;
    }

}

