<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger_info.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47; The validator node returns this structure which includes signatures
 * / from each validator to confirm the state.  The client needs to only pass
 * / back the LedgerInfo element since the validator node doesn't need to know
 * / the signatures again when the client performs a query, those are only there
 * / for the client to be able to verify the state
 *
 * Generated from protobuf message <code>types.LedgerInfoWithSignatures</code>
 */
class LedgerInfoWithSignatures extends \Google\Protobuf\Internal\Message
{
    /**
     * Signatures of the root node from each validator
     *
     * Generated from protobuf field <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    private $signatures;
    /**
     * Generated from protobuf field <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    private $ledger_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\ValidatorSignature[]|\Google\Protobuf\Internal\RepeatedField $signatures
     *           Signatures of the root node from each validator
     *     @type \Types\LedgerInfo $ledger_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedgerInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Signatures of the root node from each validator
     *
     * Generated from protobuf field <code>repeated .types.ValidatorSignature signatures = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignatures()
    {
        return $this->signatures;
    }

    /**
     * Signatures of the root node from each validator
     *
     * Generated from protobuf field <code>repeated .types.ValidatorSignature signatures = 1;</code>
     * @param \Types\ValidatorSignature[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\ValidatorSignature::class);
        $this->signatures = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.LedgerInfo ledger_info = 2;</code>
     * @return \Types\LedgerInfo
     */
    public function getLedgerInfo()
    {
        return $this->ledger_info;
    }

    /**
     * Generated from protobuf field <code>.types.LedgerInfo ledger_info = 2;</code>
     * @param \Types\LedgerInfo $var
     * @return $this
     */
    public function setLedgerInfo($var)
    {
        GPBUtil::checkMessage($var, \Types\LedgerInfo::class);
        $this->ledger_info = $var;

        return $this;
    }

}

