<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The code for the transaction to execute
 *
 * Generated from protobuf message <code>types.Program</code>
 */
class Program extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes code = 1;</code>
     */
    private $code = '';
    /**
     * Generated from protobuf field <code>repeated .types.TransactionArgument arguments = 2;</code>
     */
    private $arguments;
    /**
     * Generated from protobuf field <code>repeated bytes modules = 3;</code>
     */
    private $modules;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type \Types\TransactionArgument[]|\Google\Protobuf\Internal\RepeatedField $arguments
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $modules
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>bytes code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, False);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .types.TransactionArgument arguments = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArguments()
    {
        return $this->arguments;
    }

    /**
     * Generated from protobuf field <code>repeated .types.TransactionArgument arguments = 2;</code>
     * @param \Types\TransactionArgument[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArguments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\TransactionArgument::class);
        $this->arguments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes modules = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModules()
    {
        return $this->modules;
    }

    /**
     * Generated from protobuf field <code>repeated bytes modules = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModules($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->modules = $arr;

        return $this;
    }

}

