<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

use UnexpectedValueException;

/**
 * Protobuf type <code>types.RuntimeStatus</code>
 */
class RuntimeStatus
{
    /**
     * Generated from protobuf enum <code>UnknownRuntimeStatus = 0;</code>
     */
    const UnknownRuntimeStatus = 0;
    /**
     * Generated from protobuf enum <code>Executed = 1;</code>
     */
    const Executed = 1;
    /**
     * Generated from protobuf enum <code>OutOfGas = 2;</code>
     */
    const OutOfGas = 2;
    /**
     * We tried to access a resource that does not exist under the account.
     *
     * Generated from protobuf enum <code>ResourceDoesNotExist = 3;</code>
     */
    const ResourceDoesNotExist = 3;
    /**
     * We tried to create a resource under an account where that resource
     * already exists.
     *
     * Generated from protobuf enum <code>ResourceAlreadyExists = 4;</code>
     */
    const ResourceAlreadyExists = 4;
    /**
     * We accessed an account that is evicted.
     *
     * Generated from protobuf enum <code>EvictedAccountAccess = 5;</code>
     */
    const EvictedAccountAccess = 5;
    /**
     * We tried to create an account at an address where an account already
     * exists.
     *
     * Generated from protobuf enum <code>AccountAddressAlreadyExists = 6;</code>
     */
    const AccountAddressAlreadyExists = 6;
    /**
     * Generated from protobuf enum <code>TypeError = 7;</code>
     */
    const TypeError = 7;
    /**
     * Generated from protobuf enum <code>MissingData = 8;</code>
     */
    const MissingData = 8;
    /**
     * Generated from protobuf enum <code>DataFormatError = 9;</code>
     */
    const DataFormatError = 9;
    /**
     * Generated from protobuf enum <code>InvalidData = 10;</code>
     */
    const InvalidData = 10;
    /**
     * Generated from protobuf enum <code>RemoteDataError = 11;</code>
     */
    const RemoteDataError = 11;
    /**
     * Generated from protobuf enum <code>CannotWriteExistingResource = 12;</code>
     */
    const CannotWriteExistingResource = 12;
    /**
     * Generated from protobuf enum <code>ValueSerializationError = 13;</code>
     */
    const ValueSerializationError = 13;
    /**
     * Generated from protobuf enum <code>ValueDeserializationError = 14;</code>
     */
    const ValueDeserializationError = 14;
    /**
     * The sender is trying to publish a module named `M`, but the sender's account already contains
     * a module with this name.
     *
     * Generated from protobuf enum <code>DuplicateModuleName = 15;</code>
     */
    const DuplicateModuleName = 15;

    private static $valueToName = [
        self::UnknownRuntimeStatus => 'UnknownRuntimeStatus',
        self::Executed => 'Executed',
        self::OutOfGas => 'OutOfGas',
        self::ResourceDoesNotExist => 'ResourceDoesNotExist',
        self::ResourceAlreadyExists => 'ResourceAlreadyExists',
        self::EvictedAccountAccess => 'EvictedAccountAccess',
        self::AccountAddressAlreadyExists => 'AccountAddressAlreadyExists',
        self::TypeError => 'TypeError',
        self::MissingData => 'MissingData',
        self::DataFormatError => 'DataFormatError',
        self::InvalidData => 'InvalidData',
        self::RemoteDataError => 'RemoteDataError',
        self::CannotWriteExistingResource => 'CannotWriteExistingResource',
        self::ValueSerializationError => 'ValueSerializationError',
        self::ValueDeserializationError => 'ValueDeserializationError',
        self::DuplicateModuleName => 'DuplicateModuleName',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

