<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.SignedTransactionWithProof</code>
 */
class SignedTransactionWithProof extends \Google\Protobuf\Internal\Message
{
    /**
     * The version of the returned signed transaction.
     *
     * Generated from protobuf field <code>uint64 version = 1;</code>
     */
    private $version = 0;
    /**
     * The transaction itself.
     *
     * Generated from protobuf field <code>.types.SignedTransaction signed_transaction = 2;</code>
     */
    private $signed_transaction = null;
    /**
     * The proof authenticating the signed transaction.
     *
     * Generated from protobuf field <code>.types.SignedTransactionProof proof = 3;</code>
     */
    private $proof = null;
    /**
     * The events yielded by executing the transaction, if requested.
     *
     * Generated from protobuf field <code>.types.EventsList events = 4;</code>
     */
    private $events = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $version
     *           The version of the returned signed transaction.
     *     @type \Types\SignedTransaction $signed_transaction
     *           The transaction itself.
     *     @type \Types\SignedTransactionProof $proof
     *           The proof authenticating the signed transaction.
     *     @type \Types\EventsList $events
     *           The events yielded by executing the transaction, if requested.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * The version of the returned signed transaction.
     *
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * The version of the returned signed transaction.
     *
     * Generated from protobuf field <code>uint64 version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->version = $var;

        return $this;
    }

    /**
     * The transaction itself.
     *
     * Generated from protobuf field <code>.types.SignedTransaction signed_transaction = 2;</code>
     * @return \Types\SignedTransaction
     */
    public function getSignedTransaction()
    {
        return $this->signed_transaction;
    }

    /**
     * The transaction itself.
     *
     * Generated from protobuf field <code>.types.SignedTransaction signed_transaction = 2;</code>
     * @param \Types\SignedTransaction $var
     * @return $this
     */
    public function setSignedTransaction($var)
    {
        GPBUtil::checkMessage($var, \Types\SignedTransaction::class);
        $this->signed_transaction = $var;

        return $this;
    }

    /**
     * The proof authenticating the signed transaction.
     *
     * Generated from protobuf field <code>.types.SignedTransactionProof proof = 3;</code>
     * @return \Types\SignedTransactionProof
     */
    public function getProof()
    {
        return $this->proof;
    }

    /**
     * The proof authenticating the signed transaction.
     *
     * Generated from protobuf field <code>.types.SignedTransactionProof proof = 3;</code>
     * @param \Types\SignedTransactionProof $var
     * @return $this
     */
    public function setProof($var)
    {
        GPBUtil::checkMessage($var, \Types\SignedTransactionProof::class);
        $this->proof = $var;

        return $this;
    }

    /**
     * The events yielded by executing the transaction, if requested.
     *
     * Generated from protobuf field <code>.types.EventsList events = 4;</code>
     * @return \Types\EventsList
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * The events yielded by executing the transaction, if requested.
     *
     * Generated from protobuf field <code>.types.EventsList events = 4;</code>
     * @param \Types\EventsList $var
     * @return $this
     */
    public function setEvents($var)
    {
        GPBUtil::checkMessage($var, \Types\EventsList::class);
        $this->events = $var;

        return $this;
    }

}

