<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A generic structure that represents signed RawTransaction
 *
 * Generated from protobuf message <code>types.SignedTransaction</code>
 */
class SignedTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * The serialized Protobuf bytes for RawTransaction, for which the signature
     * was signed. Protobuf doesn't guarantee the serialized bytes is canonical
     * across different language implementations, but for our use cases for
     * transaction it is not necessary because the client is the only one to
     * produce this bytes, which is then persisted in storage.
     *
     * Generated from protobuf field <code>bytes raw_txn_bytes = 1;</code>
     */
    private $raw_txn_bytes = '';
    /**
     * public key that corresponds to RawTransaction::sender_account
     *
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     */
    private $sender_public_key = '';
    /**
     * signature for the hash
     *
     * Generated from protobuf field <code>bytes sender_signature = 3;</code>
     */
    private $sender_signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $raw_txn_bytes
     *           The serialized Protobuf bytes for RawTransaction, for which the signature
     *           was signed. Protobuf doesn't guarantee the serialized bytes is canonical
     *           across different language implementations, but for our use cases for
     *           transaction it is not necessary because the client is the only one to
     *           produce this bytes, which is then persisted in storage.
     *     @type string $sender_public_key
     *           public key that corresponds to RawTransaction::sender_account
     *     @type string $sender_signature
     *           signature for the hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * The serialized Protobuf bytes for RawTransaction, for which the signature
     * was signed. Protobuf doesn't guarantee the serialized bytes is canonical
     * across different language implementations, but for our use cases for
     * transaction it is not necessary because the client is the only one to
     * produce this bytes, which is then persisted in storage.
     *
     * Generated from protobuf field <code>bytes raw_txn_bytes = 1;</code>
     * @return string
     */
    public function getRawTxnBytes()
    {
        return $this->raw_txn_bytes;
    }

    /**
     * The serialized Protobuf bytes for RawTransaction, for which the signature
     * was signed. Protobuf doesn't guarantee the serialized bytes is canonical
     * across different language implementations, but for our use cases for
     * transaction it is not necessary because the client is the only one to
     * produce this bytes, which is then persisted in storage.
     *
     * Generated from protobuf field <code>bytes raw_txn_bytes = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRawTxnBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->raw_txn_bytes = $var;

        return $this;
    }

    /**
     * public key that corresponds to RawTransaction::sender_account
     *
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * public key that corresponds to RawTransaction::sender_account
     *
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * signature for the hash
     *
     * Generated from protobuf field <code>bytes sender_signature = 3;</code>
     * @return string
     */
    public function getSenderSignature()
    {
        return $this->sender_signature;
    }

    /**
     * signature for the hash
     *
     * Generated from protobuf field <code>bytes sender_signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender_signature = $var;

        return $this;
    }

}

