<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

if (false) {
    /**
     * This class is deprecated. Use Types\TransactionArgument\ArgType instead.
     * @deprecated
     */
    class TransactionArgument_ArgType {}
}
class_exists(TransactionArgument\ArgType::class);
@trigger_error('Types\TransactionArgument_ArgType is deprecated and will be removed in the next major release. Use Types\TransactionArgument\ArgType instead', E_USER_DEPRECATED);

