<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_with_proof.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This API is used to update the client to the latest ledger version and
 * optionally also request 1..n other pieces of data.  This allows for batch
 * queries.  All queries return proofs that a client should check to validate
 * the data.
 * Note that if a client only wishes to update to the latest LedgerInfo and
 * receive the proof that this latest ledger extends the client_known_version
 * ledger the client had, they can simply set the requested_items to an empty
 * list.
 *
 * Generated from protobuf message <code>types.UpdateToLatestLedgerRequest</code>
 */
class UpdateToLatestLedgerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * This is the version the client already trusts. Usually the client should
     * set this to the version it obtained the last time it synced with the
     * chain. If this is the first time ever the client sends a request, it must
     * use the waypoint hard-coded in its software.
     *
     * Generated from protobuf field <code>uint64 client_known_version = 1;</code>
     */
    private $client_known_version = 0;
    /**
     * The items for which we are requesting data in this API call.
     *
     * Generated from protobuf field <code>repeated .types.RequestItem requested_items = 2;</code>
     */
    private $requested_items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $client_known_version
     *           This is the version the client already trusts. Usually the client should
     *           set this to the version it obtained the last time it synced with the
     *           chain. If this is the first time ever the client sends a request, it must
     *           use the waypoint hard-coded in its software.
     *     @type \Types\RequestItem[]|\Google\Protobuf\Internal\RepeatedField $requested_items
     *           The items for which we are requesting data in this API call.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GetWithProof::initOnce();
        parent::__construct($data);
    }

    /**
     * This is the version the client already trusts. Usually the client should
     * set this to the version it obtained the last time it synced with the
     * chain. If this is the first time ever the client sends a request, it must
     * use the waypoint hard-coded in its software.
     *
     * Generated from protobuf field <code>uint64 client_known_version = 1;</code>
     * @return int|string
     */
    public function getClientKnownVersion()
    {
        return $this->client_known_version;
    }

    /**
     * This is the version the client already trusts. Usually the client should
     * set this to the version it obtained the last time it synced with the
     * chain. If this is the first time ever the client sends a request, it must
     * use the waypoint hard-coded in its software.
     *
     * Generated from protobuf field <code>uint64 client_known_version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientKnownVersion($var)
    {
        GPBUtil::checkUint64($var);
        $this->client_known_version = $var;

        return $this;
    }

    /**
     * The items for which we are requesting data in this API call.
     *
     * Generated from protobuf field <code>repeated .types.RequestItem requested_items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequestedItems()
    {
        return $this->requested_items;
    }

    /**
     * The items for which we are requesting data in this API call.
     *
     * Generated from protobuf field <code>repeated .types.RequestItem requested_items = 2;</code>
     * @param \Types\RequestItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequestedItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\RequestItem::class);
        $this->requested_items = $arr;

        return $this;
    }

}

