<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator_set.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf definition for the Rust struct ValidatorSet.
 *
 * Generated from protobuf message <code>types.ValidatorSet</code>
 */
class ValidatorSet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .types.ValidatorPublicKeys validator_public_keys = 1;</code>
     */
    private $validator_public_keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\ValidatorPublicKeys[]|\Google\Protobuf\Internal\RepeatedField $validator_public_keys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ValidatorSet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .types.ValidatorPublicKeys validator_public_keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValidatorPublicKeys()
    {
        return $this->validator_public_keys;
    }

    /**
     * Generated from protobuf field <code>repeated .types.ValidatorPublicKeys validator_public_keys = 1;</code>
     * @param \Types\ValidatorPublicKeys[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValidatorPublicKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\ValidatorPublicKeys::class);
        $this->validator_public_keys = $arr;

        return $this;
    }

}

