<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger_info.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.ValidatorSignature</code>
 */
class ValidatorSignature extends \Google\Protobuf\Internal\Message
{
    /**
     * The account address of the validator, which can be used for retrieving its
     * public key during the given epoch.
     *
     * Generated from protobuf field <code>bytes validator_id = 1;</code>
     */
    private $validator_id = '';
    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     */
    private $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $validator_id
     *           The account address of the validator, which can be used for retrieving its
     *           public key during the given epoch.
     *     @type string $signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedgerInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * The account address of the validator, which can be used for retrieving its
     * public key during the given epoch.
     *
     * Generated from protobuf field <code>bytes validator_id = 1;</code>
     * @return string
     */
    public function getValidatorId()
    {
        return $this->validator_id;
    }

    /**
     * The account address of the validator, which can be used for retrieving its
     * public key during the given epoch.
     *
     * Generated from protobuf field <code>bytes validator_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValidatorId($var)
    {
        GPBUtil::checkString($var, False);
        $this->validator_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

