<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The status of the VM
 *
 * Generated from protobuf message <code>types.VMStatus</code>
 */
class VMStatus extends \Google\Protobuf\Internal\Message
{
    protected $error_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\VMValidationStatus $validation
     *     @type \Types\VMVerificationStatusList $verification
     *     @type int $invariant_violation
     *     @type int $deserialization
     *     @type \Types\ExecutionStatus $execution
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\VmErrors::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.VMValidationStatus validation = 1;</code>
     * @return \Types\VMValidationStatus
     */
    public function getValidation()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.types.VMValidationStatus validation = 1;</code>
     * @param \Types\VMValidationStatus $var
     * @return $this
     */
    public function setValidation($var)
    {
        GPBUtil::checkMessage($var, \Types\VMValidationStatus::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.VMVerificationStatusList verification = 2;</code>
     * @return \Types\VMVerificationStatusList
     */
    public function getVerification()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.types.VMVerificationStatusList verification = 2;</code>
     * @param \Types\VMVerificationStatusList $var
     * @return $this
     */
    public function setVerification($var)
    {
        GPBUtil::checkMessage($var, \Types\VMVerificationStatusList::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.VMInvariantViolationError invariant_violation = 3;</code>
     * @return int
     */
    public function getInvariantViolation()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.types.VMInvariantViolationError invariant_violation = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setInvariantViolation($var)
    {
        GPBUtil::checkEnum($var, \Types\VMInvariantViolationError::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.BinaryError deserialization = 4;</code>
     * @return int
     */
    public function getDeserialization()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.types.BinaryError deserialization = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDeserialization($var)
    {
        GPBUtil::checkEnum($var, \Types\BinaryError::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.ExecutionStatus execution = 5;</code>
     * @return \Types\ExecutionStatus
     */
    public function getExecution()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.types.ExecutionStatus execution = 5;</code>
     * @param \Types\ExecutionStatus $var
     * @return $this
     */
    public function setExecution($var)
    {
        GPBUtil::checkMessage($var, \Types\ExecutionStatus::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getErrorType()
    {
        return $this->whichOneof("error_type");
    }

}

