<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

if (false) {
    /**
     * This class is deprecated. Use Types\VMVerificationStatus\StatusKind instead.
     * @deprecated
     */
    class VMVerificationStatus_StatusKind {}
}
class_exists(VMVerificationStatus\StatusKind::class);
@trigger_error('Types\VMVerificationStatus_StatusKind is deprecated and will be removed in the next major release. Use Types\VMVerificationStatus\StatusKind instead', E_USER_DEPRECATED);

