<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>types.VMVerificationStatus</code>
 */
class VMVerificationStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.types.VMVerificationStatus.StatusKind status_kind = 1;</code>
     */
    private $status_kind = 0;
    /**
     * For StatusKind::SCRIPT and DEPENDENCY this is ignored.
     *
     * Generated from protobuf field <code>uint32 module_idx = 2;</code>
     */
    private $module_idx = 0;
    /**
     * Generated from protobuf field <code>.types.VMVerificationErrorKind error_kind = 3;</code>
     */
    private $error_kind = 0;
    /**
     * Generated from protobuf field <code>string message = 4;</code>
     */
    private $message = '';
    /**
     * For StatusKind::SCRIPT and MODULE this is ignored.
     *
     * Generated from protobuf field <code>.types.ModuleId dependency_id = 5;</code>
     */
    private $dependency_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status_kind
     *     @type int $module_idx
     *           For StatusKind::SCRIPT and DEPENDENCY this is ignored.
     *     @type int $error_kind
     *     @type string $message
     *     @type \Types\ModuleId $dependency_id
     *           For StatusKind::SCRIPT and MODULE this is ignored.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\VmErrors::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.types.VMVerificationStatus.StatusKind status_kind = 1;</code>
     * @return int
     */
    public function getStatusKind()
    {
        return $this->status_kind;
    }

    /**
     * Generated from protobuf field <code>.types.VMVerificationStatus.StatusKind status_kind = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusKind($var)
    {
        GPBUtil::checkEnum($var, \Types\VMVerificationStatus_StatusKind::class);
        $this->status_kind = $var;

        return $this;
    }

    /**
     * For StatusKind::SCRIPT and DEPENDENCY this is ignored.
     *
     * Generated from protobuf field <code>uint32 module_idx = 2;</code>
     * @return int
     */
    public function getModuleIdx()
    {
        return $this->module_idx;
    }

    /**
     * For StatusKind::SCRIPT and DEPENDENCY this is ignored.
     *
     * Generated from protobuf field <code>uint32 module_idx = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setModuleIdx($var)
    {
        GPBUtil::checkUint32($var);
        $this->module_idx = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.types.VMVerificationErrorKind error_kind = 3;</code>
     * @return int
     */
    public function getErrorKind()
    {
        return $this->error_kind;
    }

    /**
     * Generated from protobuf field <code>.types.VMVerificationErrorKind error_kind = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorKind($var)
    {
        GPBUtil::checkEnum($var, \Types\VMVerificationErrorKind::class);
        $this->error_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * For StatusKind::SCRIPT and MODULE this is ignored.
     *
     * Generated from protobuf field <code>.types.ModuleId dependency_id = 5;</code>
     * @return \Types\ModuleId
     */
    public function getDependencyId()
    {
        return $this->dependency_id;
    }

    /**
     * For StatusKind::SCRIPT and MODULE this is ignored.
     *
     * Generated from protobuf field <code>.types.ModuleId dependency_id = 5;</code>
     * @param \Types\ModuleId $var
     * @return $this
     */
    public function setDependencyId($var)
    {
        GPBUtil::checkMessage($var, \Types\ModuleId::class);
        $this->dependency_id = $var;

        return $this;
    }

}

