<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types;

use UnexpectedValueException;

/**
 * When a code module/script is published it is verified. These are the
 * possible errors that can arise from the verification process.
 *
 * Protobuf type <code>types.VMVerificationErrorKind</code>
 */
class VMVerificationErrorKind
{
    /**
     * Likewise default to a unknown verification error
     *
     * Generated from protobuf enum <code>UnknownVerificationError = 0;</code>
     */
    const UnknownVerificationError = 0;
    /**
     * Generated from protobuf enum <code>IndexOutOfBounds = 1;</code>
     */
    const IndexOutOfBounds = 1;
    /**
     * Generated from protobuf enum <code>RangeOutOfBounds = 2;</code>
     */
    const RangeOutOfBounds = 2;
    /**
     * Generated from protobuf enum <code>InvalidSignatureToken = 3;</code>
     */
    const InvalidSignatureToken = 3;
    /**
     * Generated from protobuf enum <code>InvalidFieldDefReference = 4;</code>
     */
    const InvalidFieldDefReference = 4;
    /**
     * Generated from protobuf enum <code>RecursiveStructDefinition = 5;</code>
     */
    const RecursiveStructDefinition = 5;
    /**
     * Generated from protobuf enum <code>InvalidResourceField = 6;</code>
     */
    const InvalidResourceField = 6;
    /**
     * Generated from protobuf enum <code>InvalidFallThrough = 7;</code>
     */
    const InvalidFallThrough = 7;
    /**
     * Generated from protobuf enum <code>JoinFailure = 8;</code>
     */
    const JoinFailure = 8;
    /**
     * Generated from protobuf enum <code>NegativeStackSizeWithinBlock = 9;</code>
     */
    const NegativeStackSizeWithinBlock = 9;
    /**
     * Generated from protobuf enum <code>UnbalancedStack = 10;</code>
     */
    const UnbalancedStack = 10;
    /**
     * Generated from protobuf enum <code>InvalidMainFunctionSignature = 11;</code>
     */
    const InvalidMainFunctionSignature = 11;
    /**
     * Generated from protobuf enum <code>DuplicateElement = 12;</code>
     */
    const DuplicateElement = 12;
    /**
     * Generated from protobuf enum <code>InvalidModuleHandle = 13;</code>
     */
    const InvalidModuleHandle = 13;
    /**
     * Generated from protobuf enum <code>UnimplementedHandle = 14;</code>
     */
    const UnimplementedHandle = 14;
    /**
     * Generated from protobuf enum <code>InconsistentFields = 15;</code>
     */
    const InconsistentFields = 15;
    /**
     * Generated from protobuf enum <code>UnusedFields = 16;</code>
     */
    const UnusedFields = 16;
    /**
     * Generated from protobuf enum <code>LookupFailed = 17;</code>
     */
    const LookupFailed = 17;
    /**
     * Generated from protobuf enum <code>VisibilityMismatch = 18;</code>
     */
    const VisibilityMismatch = 18;
    /**
     * Generated from protobuf enum <code>TypeResolutionFailure = 19;</code>
     */
    const TypeResolutionFailure = 19;
    /**
     * Generated from protobuf enum <code>TypeMismatch = 20;</code>
     */
    const TypeMismatch = 20;
    /**
     * Generated from protobuf enum <code>MissingDependency = 21;</code>
     */
    const MissingDependency = 21;
    /**
     * Generated from protobuf enum <code>PopReferenceError = 22;</code>
     */
    const PopReferenceError = 22;
    /**
     * Generated from protobuf enum <code>PopResourceError = 23;</code>
     */
    const PopResourceError = 23;
    /**
     * Generated from protobuf enum <code>ReleaseRefTypeMismatchError = 24;</code>
     */
    const ReleaseRefTypeMismatchError = 24;
    /**
     * Generated from protobuf enum <code>BrTypeMismatchError = 25;</code>
     */
    const BrTypeMismatchError = 25;
    /**
     * Generated from protobuf enum <code>AbortTypeMismatchError = 26;</code>
     */
    const AbortTypeMismatchError = 26;
    /**
     * Generated from protobuf enum <code>StLocTypeMismatchError = 27;</code>
     */
    const StLocTypeMismatchError = 27;
    /**
     * Generated from protobuf enum <code>StLocUnsafeToDestroyError = 28;</code>
     */
    const StLocUnsafeToDestroyError = 28;
    /**
     * Generated from protobuf enum <code>RetUnsafeToDestroyError = 29;</code>
     */
    const RetUnsafeToDestroyError = 29;
    /**
     * Generated from protobuf enum <code>RetTypeMismatchError = 30;</code>
     */
    const RetTypeMismatchError = 30;
    /**
     * Generated from protobuf enum <code>FreezeRefTypeMismatchError = 31;</code>
     */
    const FreezeRefTypeMismatchError = 31;
    /**
     * Generated from protobuf enum <code>FreezeRefExistsMutableBorrowError = 32;</code>
     */
    const FreezeRefExistsMutableBorrowError = 32;
    /**
     * Generated from protobuf enum <code>BorrowFieldTypeMismatchError = 33;</code>
     */
    const BorrowFieldTypeMismatchError = 33;
    /**
     * Generated from protobuf enum <code>BorrowFieldBadFieldError = 34;</code>
     */
    const BorrowFieldBadFieldError = 34;
    /**
     * Generated from protobuf enum <code>BorrowFieldExistsMutableBorrowError = 35;</code>
     */
    const BorrowFieldExistsMutableBorrowError = 35;
    /**
     * Generated from protobuf enum <code>CopyLocUnavailableError = 36;</code>
     */
    const CopyLocUnavailableError = 36;
    /**
     * Generated from protobuf enum <code>CopyLocResourceError = 37;</code>
     */
    const CopyLocResourceError = 37;
    /**
     * Generated from protobuf enum <code>CopyLocExistsBorrowError = 38;</code>
     */
    const CopyLocExistsBorrowError = 38;
    /**
     * Generated from protobuf enum <code>MoveLocUnavailableError = 39;</code>
     */
    const MoveLocUnavailableError = 39;
    /**
     * Generated from protobuf enum <code>MoveLocExistsBorrowError = 40;</code>
     */
    const MoveLocExistsBorrowError = 40;
    /**
     * Generated from protobuf enum <code>BorrowLocReferenceError = 41;</code>
     */
    const BorrowLocReferenceError = 41;
    /**
     * Generated from protobuf enum <code>BorrowLocUnavailableError = 42;</code>
     */
    const BorrowLocUnavailableError = 42;
    /**
     * Generated from protobuf enum <code>BorrowLocExistsBorrowError = 43;</code>
     */
    const BorrowLocExistsBorrowError = 43;
    /**
     * Generated from protobuf enum <code>CallTypeMismatchError = 44;</code>
     */
    const CallTypeMismatchError = 44;
    /**
     * Generated from protobuf enum <code>CallBorrowedMutableReferenceError = 45;</code>
     */
    const CallBorrowedMutableReferenceError = 45;
    /**
     * Generated from protobuf enum <code>PackTypeMismatchError = 46;</code>
     */
    const PackTypeMismatchError = 46;
    /**
     * Generated from protobuf enum <code>UnpackTypeMismatchError = 47;</code>
     */
    const UnpackTypeMismatchError = 47;
    /**
     * Generated from protobuf enum <code>ReadRefTypeMismatchError = 48;</code>
     */
    const ReadRefTypeMismatchError = 48;
    /**
     * Generated from protobuf enum <code>ReadRefResourceError = 49;</code>
     */
    const ReadRefResourceError = 49;
    /**
     * Generated from protobuf enum <code>ReadRefExistsMutableBorrowError = 50;</code>
     */
    const ReadRefExistsMutableBorrowError = 50;
    /**
     * Generated from protobuf enum <code>WriteRefTypeMismatchError = 51;</code>
     */
    const WriteRefTypeMismatchError = 51;
    /**
     * Generated from protobuf enum <code>WriteRefResourceError = 52;</code>
     */
    const WriteRefResourceError = 52;
    /**
     * Generated from protobuf enum <code>WriteRefExistsBorrowError = 53;</code>
     */
    const WriteRefExistsBorrowError = 53;
    /**
     * Generated from protobuf enum <code>WriteRefNoMutableReferenceError = 54;</code>
     */
    const WriteRefNoMutableReferenceError = 54;
    /**
     * Generated from protobuf enum <code>IntegerOpTypeMismatchError = 55;</code>
     */
    const IntegerOpTypeMismatchError = 55;
    /**
     * Generated from protobuf enum <code>BooleanOpTypeMismatchError = 56;</code>
     */
    const BooleanOpTypeMismatchError = 56;
    /**
     * Generated from protobuf enum <code>EqualityOpTypeMismatchError = 57;</code>
     */
    const EqualityOpTypeMismatchError = 57;
    /**
     * Generated from protobuf enum <code>ExistsResourceTypeMismatchError = 58;</code>
     */
    const ExistsResourceTypeMismatchError = 58;
    /**
     * Generated from protobuf enum <code>BorrowGlobalTypeMismatchError = 59;</code>
     */
    const BorrowGlobalTypeMismatchError = 59;
    /**
     * Generated from protobuf enum <code>BorrowGlobalNoResourceError = 60;</code>
     */
    const BorrowGlobalNoResourceError = 60;
    /**
     * Generated from protobuf enum <code>MoveFromTypeMismatchError = 61;</code>
     */
    const MoveFromTypeMismatchError = 61;
    /**
     * Generated from protobuf enum <code>MoveFromNoResourceError = 62;</code>
     */
    const MoveFromNoResourceError = 62;
    /**
     * Generated from protobuf enum <code>MoveToSenderTypeMismatchError = 63;</code>
     */
    const MoveToSenderTypeMismatchError = 63;
    /**
     * Generated from protobuf enum <code>MoveToSenderNoResourceError = 64;</code>
     */
    const MoveToSenderNoResourceError = 64;
    /**
     * Generated from protobuf enum <code>CreateAccountTypeMismatchError = 65;</code>
     */
    const CreateAccountTypeMismatchError = 65;
    /**
     * The self address of a module the transaction is publishing is not the sender address
     *
     * Generated from protobuf enum <code>ModuleAddressDoesNotMatchSender = 66;</code>
     */
    const ModuleAddressDoesNotMatchSender = 66;
    /**
     * The module does not have any module handles. Each module or script must have at least one module handle.
     *
     * Generated from protobuf enum <code>NoModuleHandles = 67;</code>
     */
    const NoModuleHandles = 67;

    private static $valueToName = [
        self::UnknownVerificationError => 'UnknownVerificationError',
        self::IndexOutOfBounds => 'IndexOutOfBounds',
        self::RangeOutOfBounds => 'RangeOutOfBounds',
        self::InvalidSignatureToken => 'InvalidSignatureToken',
        self::InvalidFieldDefReference => 'InvalidFieldDefReference',
        self::RecursiveStructDefinition => 'RecursiveStructDefinition',
        self::InvalidResourceField => 'InvalidResourceField',
        self::InvalidFallThrough => 'InvalidFallThrough',
        self::JoinFailure => 'JoinFailure',
        self::NegativeStackSizeWithinBlock => 'NegativeStackSizeWithinBlock',
        self::UnbalancedStack => 'UnbalancedStack',
        self::InvalidMainFunctionSignature => 'InvalidMainFunctionSignature',
        self::DuplicateElement => 'DuplicateElement',
        self::InvalidModuleHandle => 'InvalidModuleHandle',
        self::UnimplementedHandle => 'UnimplementedHandle',
        self::InconsistentFields => 'InconsistentFields',
        self::UnusedFields => 'UnusedFields',
        self::LookupFailed => 'LookupFailed',
        self::VisibilityMismatch => 'VisibilityMismatch',
        self::TypeResolutionFailure => 'TypeResolutionFailure',
        self::TypeMismatch => 'TypeMismatch',
        self::MissingDependency => 'MissingDependency',
        self::PopReferenceError => 'PopReferenceError',
        self::PopResourceError => 'PopResourceError',
        self::ReleaseRefTypeMismatchError => 'ReleaseRefTypeMismatchError',
        self::BrTypeMismatchError => 'BrTypeMismatchError',
        self::AbortTypeMismatchError => 'AbortTypeMismatchError',
        self::StLocTypeMismatchError => 'StLocTypeMismatchError',
        self::StLocUnsafeToDestroyError => 'StLocUnsafeToDestroyError',
        self::RetUnsafeToDestroyError => 'RetUnsafeToDestroyError',
        self::RetTypeMismatchError => 'RetTypeMismatchError',
        self::FreezeRefTypeMismatchError => 'FreezeRefTypeMismatchError',
        self::FreezeRefExistsMutableBorrowError => 'FreezeRefExistsMutableBorrowError',
        self::BorrowFieldTypeMismatchError => 'BorrowFieldTypeMismatchError',
        self::BorrowFieldBadFieldError => 'BorrowFieldBadFieldError',
        self::BorrowFieldExistsMutableBorrowError => 'BorrowFieldExistsMutableBorrowError',
        self::CopyLocUnavailableError => 'CopyLocUnavailableError',
        self::CopyLocResourceError => 'CopyLocResourceError',
        self::CopyLocExistsBorrowError => 'CopyLocExistsBorrowError',
        self::MoveLocUnavailableError => 'MoveLocUnavailableError',
        self::MoveLocExistsBorrowError => 'MoveLocExistsBorrowError',
        self::BorrowLocReferenceError => 'BorrowLocReferenceError',
        self::BorrowLocUnavailableError => 'BorrowLocUnavailableError',
        self::BorrowLocExistsBorrowError => 'BorrowLocExistsBorrowError',
        self::CallTypeMismatchError => 'CallTypeMismatchError',
        self::CallBorrowedMutableReferenceError => 'CallBorrowedMutableReferenceError',
        self::PackTypeMismatchError => 'PackTypeMismatchError',
        self::UnpackTypeMismatchError => 'UnpackTypeMismatchError',
        self::ReadRefTypeMismatchError => 'ReadRefTypeMismatchError',
        self::ReadRefResourceError => 'ReadRefResourceError',
        self::ReadRefExistsMutableBorrowError => 'ReadRefExistsMutableBorrowError',
        self::WriteRefTypeMismatchError => 'WriteRefTypeMismatchError',
        self::WriteRefResourceError => 'WriteRefResourceError',
        self::WriteRefExistsBorrowError => 'WriteRefExistsBorrowError',
        self::WriteRefNoMutableReferenceError => 'WriteRefNoMutableReferenceError',
        self::IntegerOpTypeMismatchError => 'IntegerOpTypeMismatchError',
        self::BooleanOpTypeMismatchError => 'BooleanOpTypeMismatchError',
        self::EqualityOpTypeMismatchError => 'EqualityOpTypeMismatchError',
        self::ExistsResourceTypeMismatchError => 'ExistsResourceTypeMismatchError',
        self::BorrowGlobalTypeMismatchError => 'BorrowGlobalTypeMismatchError',
        self::BorrowGlobalNoResourceError => 'BorrowGlobalNoResourceError',
        self::MoveFromTypeMismatchError => 'MoveFromTypeMismatchError',
        self::MoveFromNoResourceError => 'MoveFromNoResourceError',
        self::MoveToSenderTypeMismatchError => 'MoveToSenderTypeMismatchError',
        self::MoveToSenderNoResourceError => 'MoveToSenderNoResourceError',
        self::CreateAccountTypeMismatchError => 'CreateAccountTypeMismatchError',
        self::ModuleAddressDoesNotMatchSender => 'ModuleAddressDoesNotMatchSender',
        self::NoModuleHandles => 'NoModuleHandles',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

