<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Write Operation on underlying storage.
 *
 * Generated from protobuf message <code>types.WriteOp</code>
 */
class WriteOp extends \Google\Protobuf\Internal\Message
{
    /**
     * AccessPath of the write set.
     *
     * Generated from protobuf field <code>.types.AccessPath access_path = 1;</code>
     */
    private $access_path = null;
    /**
     * The value of the write op. Empty if `type` is Delete.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     */
    private $value = '';
    /**
     * WriteOp type.
     *
     * Generated from protobuf field <code>.types.WriteOpType type = 3;</code>
     */
    private $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\AccessPath $access_path
     *           AccessPath of the write set.
     *     @type string $value
     *           The value of the write op. Empty if `type` is Delete.
     *     @type int $type
     *           WriteOp type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * AccessPath of the write set.
     *
     * Generated from protobuf field <code>.types.AccessPath access_path = 1;</code>
     * @return \Types\AccessPath
     */
    public function getAccessPath()
    {
        return $this->access_path;
    }

    /**
     * AccessPath of the write set.
     *
     * Generated from protobuf field <code>.types.AccessPath access_path = 1;</code>
     * @param \Types\AccessPath $var
     * @return $this
     */
    public function setAccessPath($var)
    {
        GPBUtil::checkMessage($var, \Types\AccessPath::class);
        $this->access_path = $var;

        return $this;
    }

    /**
     * The value of the write op. Empty if `type` is Delete.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value of the write op. Empty if `type` is Delete.
     *
     * Generated from protobuf field <code>bytes value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->value = $var;

        return $this;
    }

    /**
     * WriteOp type.
     *
     * Generated from protobuf field <code>.types.WriteOpType type = 3;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * WriteOp type.
     *
     * Generated from protobuf field <code>.types.WriteOpType type = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Types\WriteOpType::class);
        $this->type = $var;

        return $this;
    }

}

