<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Set of WriteOps to save to storage.
 *
 * Generated from protobuf message <code>types.WriteSet</code>
 */
class WriteSet extends \Google\Protobuf\Internal\Message
{
    /**
     * Set of WriteOp for storage update.
     *
     * Generated from protobuf field <code>repeated .types.WriteOp write_set = 1;</code>
     */
    private $write_set;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\WriteOp[]|\Google\Protobuf\Internal\RepeatedField $write_set
     *           Set of WriteOp for storage update.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Set of WriteOp for storage update.
     *
     * Generated from protobuf field <code>repeated .types.WriteOp write_set = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWriteSet()
    {
        return $this->write_set;
    }

    /**
     * Set of WriteOp for storage update.
     *
     * Generated from protobuf field <code>repeated .types.WriteOp write_set = 1;</code>
     * @param \Types\WriteOp[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWriteSet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Types\WriteOp::class);
        $this->write_set = $arr;

        return $this;
    }

}

