<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Types;

use UnexpectedValueException;

/**
 * Type of write operation
 *
 * Protobuf type <code>types.WriteOpType</code>
 */
class WriteOpType
{
    /**
     * The WriteOp is to create/update the field from storage.
     *
     * Generated from protobuf enum <code>Write = 0;</code>
     */
    const Write = 0;
    /**
     * The WriteOp is to delete the field from storage.
     *
     * Generated from protobuf enum <code>Delete = 1;</code>
     */
    const Delete = 1;

    private static $valueToName = [
        self::Write => 'Write',
        self::Delete => 'Delete',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

