<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admission_control.proto

namespace Admission_control;

use UnexpectedValueException;

/**
 * Additional statuses that are possible from admission control in addition
 * to VM statuses.
 *
 * Protobuf type <code>admission_control.AdmissionControlStatus</code>
 */
class AdmissionControlStatus
{
    /**
     * Generated from protobuf enum <code>Accepted = 0;</code>
     */
    const Accepted = 0;
    /**
     * Generated from protobuf enum <code>Blacklisted = 1;</code>
     */
    const Blacklisted = 1;
    /**
     * Generated from protobuf enum <code>Rejected = 2;</code>
     */
    const Rejected = 2;

    private static $valueToName = [
        self::Accepted => 'Accepted',
        self::Blacklisted => 'Blacklisted',
        self::Rejected => 'Rejected',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

