<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admission_control.proto

namespace Admission_control;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * -----------------------------------------------------------------------------
 * ---------------- Submit transaction
 * -----------------------------------------------------------------------------
 * The request for transaction submission.
 *
 * Generated from protobuf message <code>admission_control.SubmitTransactionRequest</code>
 */
class SubmitTransactionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Transaction signed by wallet.
     *
     * Generated from protobuf field <code>.types.SignedTransaction signed_txn = 1;</code>
     */
    private $signed_txn = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Types\SignedTransaction $signed_txn
     *           Transaction signed by wallet.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AdmissionControl::initOnce();
        parent::__construct($data);
    }

    /**
     * Transaction signed by wallet.
     *
     * Generated from protobuf field <code>.types.SignedTransaction signed_txn = 1;</code>
     * @return \Types\SignedTransaction
     */
    public function getSignedTxn()
    {
        return $this->signed_txn;
    }

    /**
     * Transaction signed by wallet.
     *
     * Generated from protobuf field <code>.types.SignedTransaction signed_txn = 1;</code>
     * @param \Types\SignedTransaction $var
     * @return $this
     */
    public function setSignedTxn($var)
    {
        GPBUtil::checkMessage($var, \Types\SignedTransaction::class);
        $this->signed_txn = $var;

        return $this;
    }

}

