<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

namespace Types\VMVerificationStatus;

use UnexpectedValueException;

/**
 * Protobuf type <code>types.VMVerificationStatus.StatusKind</code>
 */
class StatusKind
{
    /**
     * Generated from protobuf enum <code>SCRIPT = 0;</code>
     */
    const SCRIPT = 0;
    /**
     * Generated from protobuf enum <code>MODULE = 1;</code>
     */
    const MODULE = 1;
    /**
     * Generated from protobuf enum <code>DEPENDENCY = 2;</code>
     */
    const DEPENDENCY = 2;

    private static $valueToName = [
        self::SCRIPT => 'SCRIPT',
        self::MODULE => 'MODULE',
        self::DEPENDENCY => 'DEPENDENCY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StatusKind::class, \Types\VMVerificationStatus_StatusKind::class);

